-- CREATE TABLE users (
--     user_id int primary key generated by default as identity,
--     email character(50) NOT NULL unique ,
--     full_name character(50) NOT NULL,
--     password character(8) NOT NULL,
--     enabled int DEFAULT NULL
--     );
--
-- CREATE TABLE roles (
--     role_id int primary key generated by default as identity,
--     name character(50) NOT NULL
--     );
--
-- CREATE TABLE users_roles (
--     user_id int NOT NULL,
--     role_id int NOT NULL,
--     primary key (user_id, role_id),
--     foreign key (user_id) references users(user_id) on delete set null,
--     foreign key (role_id) references roles(role_id) on delete set null
--     );

CREATE TABLE booking
(
    id  int primary key generated by default as identity,
    fio character(50) NOT NULL,
    age int DEFAULT NULL
)
